appName : API Publisher
theme : "org.wso2.carbon.apimgt.web.publisher.theme.default"
title : "API Publisher Application"
errorPages:
  "404": /foundation/error/404
  default: /foundation/error/default
loginPageUri: "/login"
loginRedirectUri: "/apis"
scopes: "apim:api_view"
tokenEndpoint: "https://apis.wso2.com/apimanager/token"
keyAndSecret: "dmRNdk05d1R4NkZ5NjNXa2xfb0FEaTdMQXZnYTp3UHNIQkJFS1FPbWU0bGZxYlJRZW1GY3ZqSUlh=="
swaggerUrl: "/publisher/public/components/root/base/js/swagger.json"
nonSecureUrl: "/test1,/test2"
