appName : API Publisher
theme : "org.wso2.carbon.apimgt.web.publisher.theme.default"
title : "API Publisher Application"
errorPages:
  "404": /foundation/error/404
  default: /foundation/error/default
loginPageUri: "/login"
loginRedirectUri: "/apis"
key: ""
secret: ""
nonSecureUrl: "/test1,/test2"
