appName: Publisher Commons
# TODO: publisher common name ui is sheduled to be change with the UUF mvn plugin update ~tmkb
loginPageUri: "/ui/login"
loginRedirectUri: "/apis"
scopes: "apim:api_view"
tokenEndpoint: "https://localhost:8243/token"
keyAndSecret: "dmRNdk05d1R4NkZ5NjNXa2xfb0FEaTdMQXZnYTp3UHNIQkJFS1FPbWU0bGZxYlJRZW1GY3ZqSUlh=="
swaggerUrl: "https://localhost:9443/api/am/publisher/v0.10/swagger.json"
nonSecureUrl: "/test1,/test2"
