appName: Publisher Commons
# TODO: publisher common name ui is sheduled to be change with the UUF mvn plugin update ~tmkb
loginPageUri: "/ui/login"
loginRedirectUri: "/apis"
scopes: "apim:api_view"
tokenEndpoint: "https://apis.wso2.com/apimanager/token"
keyAndSecret: "dmRNdk05d1R4NkZ5NjNXa2xfb0FEaTdMQXZnYTp3UHNIQkJFS1FPbWU0bGZxYlJRZW1GY3ZqSUlh=="
swaggerUrl: "/publisher/public/components/root/base/js/swagger.json"
nonSecureUrl: "/test1,/test2"
